spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

mybatis:
  type-aliases-package: board.demo.dto
  configuration.map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080